### PR TITLE
fix: inline math rendering

### LINKED ISSUE #161: Issue with inline math rendering
I don't know from when it has appeared, but there is a vertical alignment issue with inline math rendering. For instance https://luxdl.github.io/DocumenterVitepress.jl/dev/markdown-examples#equations .

It appears on several browsers on different devices and OS.

### PR DESCRIPTION
**Pull request by thofma**
Closes #161.

P.S.: The github online editor added the newline. Not sure if this is goo or bad.

### CODE REVIEW

**Comment by Azzaare** [comment]
I would really appreciate it if someone could review and, if appropriate, merge this PR.

Thank you @thofma

**Comment by asinghvi17** [comment]
Thanks @thofma!  (And @Azzaare for the reminder :D)

**Comment by oameye** [comment]
Can we tag a new release such that this commit becomes available :)

**Comment by oameye** [comment]
Realized I can just change the style.css file myself :)

**Pull request merged**
