### PR TITLE
Fix links/Markdown in headings

### PR DESCRIPTION
**Pull request by asinghvi17**
Try to fix Markdown heading rendering, by only rendering the anchor string if it's equivalent to the rendered text.  Not quite there yet...

### CODE REVIEW

**Comment by asinghvi17** [comment]
@avik-pal this might fix the issue you've been having!

**Comment by asinghvi17** [comment]
Will merge tomorrow afternoon if no comments!

**Comment by avik-pal** [comment]
Missed this. Let me trigger a build with this branch

**Comment by avik-pal** [comment]
You can go ahead with this, for some reason the documentation CI in Lux is not correctly installing the Manifest.

**Pull request merged**
