### PR TITLE
Remove these space cadet fonts 🐵

### LINKED ISSUE #57: `@` sign looks funny in code blocks [personal preference]
I don't like how the `@` sign looks in code blocks.

Screenshot from 2024-03-04 10-13-07

Screenshot from 2024-03-04 10-14-13

I prefer `@` signs more similar to [julia mono](https://juliamono.netlify.app/)

Screenshot from 2024-03-04 10-15-55

This issue is entirely opinion and preference based and has no basis in facts.

### PR DESCRIPTION
**Pull request by asinghvi17**
Fixes #57

### CODE REVIEW

**Review by LilithHafner — APPROVED** [review]
The monospaced font looks much better in the preview than on 0.0.10 imo.

**Comment by asinghvi17** [comment]
I just added JuliaMono as the monospace font.  How does it look now?

**Comment by lazarusA** [comment]
It looks good. 

Maybe we should add a one liner with several characters (most use ones) so we can see how they will be rendered. Doing `help` already gives some(may not enough):

```Julia
 | | |_| | | | (_| |  |  Version 1.10.2 (2024-03-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

help?> 
search:  ] [ = $ ; ( @ { " ) ? . } ⊽ ⊼ ⊻ ⊋ ⊊ ⊉ ⊈ ⊇ ⊆ ≥ ≤ ≢ ≡ ≠ ≉ ≈ ∪ ∩ ∜ ∛ √ ∘ ∌

  Welcome to Julia 1.10.2. The full manual is available at

  https://docs.julialang.org

  as well as many great tutorials and learning resources:

  https://julialang.org/learning/

  For help on a specific function or macro, type ? followed by its name, e.g.
  ?cos, or ?@time, and press enter. Type ; to enter shell mode, ] to enter
  package mode.

  To exit the interactive session, type CTRL-D (press the control key together
  with the d key), or type exit().
```

**Comment by Moelf** [comment]
image
image


is `|>` also an instance of Space Mono font acting up?

**Comment by asinghvi17** [comment]
Yes I think so.  Not sure why this didn't transfer to `template`, maybe it just needs to be copied there...

**Comment by Moelf** [comment]
there should exist an API for "populating docs/ with template so I can edit it"

**Comment by Moelf** [comment]
https://github.com/LuxDL/DocumenterVitepress.jl/blob/1860fc25a03d15c3a032362cfbaa64e64d58e642/template/src/.vitepress/theme/style.css#L29

what about this

**Pull request merged**
