### PR TITLE
wider layout, is it better?

### PR DESCRIPTION
**Pull request by lazarusA**
This should gives additional space. Similar to the width from vanilla Documenter.

### CODE REVIEW

**Comment by asinghvi17** [comment]
I can see arguments both for and against.  Let's get some test branches on other repos with this, to see how it looks?  I can do GeoMakie for example, and probably DimensionalData is a good bet as well...

**Comment by asinghvi17** [comment]
https://github.com/MakieOrg/GeoMakie.jl/pull/252
https://github.com/JuliaGeo/GeometryOps.jl/pull/166

**Comment by avik-pal** [comment]
+1 for this. If not by default (personally, I think this is a better default), we should have an option to opt-in to this format.

Currently the navigation bar seems to be aligned incorrectly

**Comment by avik-pal** [comment]
Also maybe a little more spacing on the left? The anchors ("#") seem almost too close to the left sidebar

**Comment by thofma** [comment]
+1 from me! I tried to do this a while ago, but got lost in a web of Vitepress issues and css hell.

**Comment by lazarusA** [comment]
> +1 for this. If not by default (personally, I think this is a better default), we should have an option to opt-in to this format.
> 
> Currently the navigation bar seems to be aligned incorrectly

Ok. Latest commit should give better paddings. @asinghvi17 it looks like your tests are not using this branch, or is not using the style from the template.

If there is not more feedback, this should be good to go. Thanks everyone for chiming in 😄 .

**Comment by asinghvi17** [comment]
Yeah the style isn't applied.  Will fix that.

**Comment by avik-pal** [comment]
> Ok. Latest commit should give better padding

Yeah padding seems fixed. 

image

See the gap between the navigation bar and the left sidebar. And the line separating the Package Name from the headers in the sidebar seems to overflow into the text area.

**Comment by lazarusA** [comment]
really good catch! Latest commit should fix that.

**Comment by avik-pal** [comment]
Looks quite nice https://lux.csail.mit.edu/previews/PR721/tutorials/ :tada:

**Comment by lazarusA** [comment]
mmm... I'm still not happy with the left side paddings. 
Screenshot 2024-06-22 at 22 13 18

I need to match the width the default values.  Looks cool, but it is too small.

**Comment by avik-pal** [comment]
> Also, I would do only "Documentation" and not "Lux.jl Documentation", you already have the logo for the first part.

Good point!

**Comment by lazarusA** [comment]
Ok, final version, it turns out we only need this:

```css

.VPDoc.has-aside .content-container {
  max-width: 100% !important;
}
.aside {
  max-width: 200px !important;
  padding-left: 0 !important;
}
.VPDoc {
  padding-top: 15px !important;
  padding-left: 5px !important;

}
/* This one does the right menu */

.VPDocOutlineItem li {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
  max-width: 200px;
}

.VPNavBar .title {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}

```

the previous approach expands the whole available screen (which is fine, maybe?), but this last one keeps the content centered while also having a wider area for it. Hence, I will settled for this and merge 😄 .

**Pull request merged**
